// File generated by FlutterFire CLI.
// Directory: lib/
// File: firebase_options.dart
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUgV2rQIJQdRfw-4PEzIKDOevnTB7dyhM',
    appId: '1:1072895754121:web:2fb4da14999cb0d977ab58',
    messagingSenderId: '1072895754121',
    projectId: 'account-ai-32915',
    authDomain: 'account-ai-32915.firebaseapp.com',
    storageBucket: 'account-ai-32915.firebasestorage.app',
    measurementId: 'G-24RVVHDE38',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQPQfN3g_R57hfS3afVA9omSUYo-rZoyc',
    appId: '1:1072895754121:android:c62cea3e5e38717d77ab58',
    messagingSenderId: '1072895754121',
    projectId: 'account-ai-32915',
    storageBucket: 'account-ai-32915.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0JWR2F-Z5Pno1xjdadMj8uxH_E5OVa7w',
    appId: '1:1072895754121:ios:a311d42bd342db4b77ab58',
    messagingSenderId: '1072895754121',
    projectId: 'account-ai-32915',
    storageBucket: 'account-ai-32915.firebasestorage.app',
    iosBundleId: 'com.example.aiAccountingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0JWR2F-Z5Pno1xjdadMj8uxH_E5OVa7w',
    appId: '1:1072895754121:ios:a311d42bd342db4b77ab58',
    messagingSenderId: '1072895754121',
    projectId: 'account-ai-32915',
    storageBucket: 'account-ai-32915.firebasestorage.app',
    iosBundleId: 'com.example.aiAccountingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUgV2rQIJQdRfw-4PEzIKDOevnTB7dyhM',
    appId: '1:1072895754121:web:715742f3c71b76f277ab58',
    messagingSenderId: '1072895754121',
    projectId: 'account-ai-32915',
    authDomain: 'account-ai-32915.firebaseapp.com',
    storageBucket: 'account-ai-32915.firebasestorage.app',
    measurementId: 'G-LWP0711N3K',
  );
}
